# Generated by Django 4.0.4 on 2023-04-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('uid', models.IntegerField()),
                ('name', models.CharField(default='null', max_length=20)),
                ('address_title', models.CharField(default='null', max_length=20)),
                ('address_content', models.CharField(default='null', max_length=50)),
                ('latitude', models.FloatField(default='0.0')),
                ('longitude', models.FloatField(default='0.0')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('uid', models.IntegerField()),
                ('name', models.CharField(default='null', max_length=20)),
                ('wastetype', models.CharField(max_length=20)),
                ('date', models.DateField(verbose_name='Y-m-d')),
                ('booking_address_title', models.CharField(default='null', max_length=20)),
                ('booking_address', models.CharField(default='null', max_length=100)),
                ('booking_status', models.CharField(max_length=20)),
                ('booking_latitude', models.FloatField(default='0.0')),
                ('booking_longitude', models.FloatField(default='0.0')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBin',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('uid', models.IntegerField()),
                ('name', models.CharField(default='null', max_length=20)),
                ('amount', models.IntegerField()),
                ('address', models.CharField(default='null', max_length=50)),
                ('returnsbin', models.CharField(default='null', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Redeem',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='redeem_photos/')),
                ('description', models.CharField(max_length=100)),
                ('order_type', models.CharField(choices=[('trending', 'trending'), ('ongoing', 'ongoing')], max_length=10)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('uid', models.IntegerField()),
                ('name', models.CharField(default='null', max_length=20)),
                ('photo', models.ImageField(upload_to='report_photos/')),
                ('address_report', models.CharField(default='null', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(default='null', max_length=50)),
                ('coins', models.IntegerField(default=0)),
                ('occupation', models.CharField(max_length=20)),
            ],
        ),
    ]
